### ISSUE TITLE
Crash when training RNN model - tensorflow.python.framework.errors_impl.CancelledError:  [_Derived_]RecvAsync is cancelled. 

### ISSUE THREAD

**Issue by mfrey777** [ROCmSoftwarePlatform/tensorflow-upstream#690]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Elementary OS (based on Ubuntu 18.04)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0 (pip install tensorflow-rocm)
- Python version:3.7.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- ROCm/MIOpen version: 2.9
- GPU model and memory: Vega 56 8Gb
- CPU / RAM : Ryzen 5 3600 / 32 Gb Ram

**Describe the current behavior**
Crash shortly after training is started (in the 1st epoch): Error is the following:
tensorflow.python.framework.errors_impl.CancelledError:  [_Derived_]RecvAsync is cancelled.
         [[{{node Adam/Adam/update/AssignSubVariableOp/_41}}]]
         [[Reshape_11/_38]] [Op:__inference_distributed_function_6315]

Function call stack:
distributed_function
**Describe the expected behavior**

**Code to reproduce the issue**

This code is coming from official tensorflow tutorial here:
https://www.tensorflow.org/tutorials/text/text_classification_rnn

```
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow_datasets as tfds
import tensorflow as tf

import matplotlib.pyplot as plt

def plot_graphs(history, string):
  plt.plot(history.history[string])
  plt.plot(history.history['val_'+string], '')
  plt.xlabel("Epochs")
  plt.ylabel(string)
  plt.legend([string, 'val_'+string])
  plt.show()

dataset, info = tfds.load('imdb_reviews/subwords8k', with_info=True,
                          as_supervised=True)
train_dataset, test_dataset = dataset['train'], dataset['test']

encoder = info.features['text'].encoder
print ('Vocabulary size: {}'.format(encoder.vocab_size))

sample_string = 'Hello TensorFlow.'

encoded_string = encoder.encode(sample_string)
print ('Encoded string is {}'.format(encoded_string))
original_string = encoder.decode(encoded_string)
print ('The original string: "{}"'.format(original_string))
assert original_string == sample_string
for index in encoded_string:
  print ('{} ----> {}'.format(index, encoder.decode([index])))

BUFFER_SIZE = 10000
BATCH_SIZE = 64

train_dataset = train_dataset.shuffle(BUFFER_SIZE)
train_dataset = train_dataset.padded_batch(BATCH_SIZE, train_dataset.output_shapes)

test_dataset = test_dataset.padded_batch(BATCH_SIZE, test_dataset.output_shapes)

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(encoder.vocab_size, 64),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy',
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])

history = model.fit(train_dataset, epochs=10,
                    validation_data=test_dataset, 
                    validation_steps=30)
```

**Other info / logs**
The issue seems to be GPU related. If I run the same code on a tensorflow 2.0.0 without rocm, the code runs on the CPU and it does not crash

**Comment by mfrey777** [comment]
Just a few more infos. I realised that my linux was running a 5.XX kernel which is not not supported according to ROCM 2.9 installation guide.

So I tried to runt he same code on a Ubuntu 18.04 with a 4.15.66 kernel (and ROCM 2.9 dkms installed). 

I get the exact same error message than aboce:

The error message in the first post is the end of it, it however looks like the row below is actually the first row causing the the error.

2019-11-02 21:00:45.034231: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cudnn_rnn_ops.cc:1491 : Unimplemented: createRnnDescriptor is unimplemented

What is strange, is that I can run ANN and CNN succesfully, but the 2 times I tries to run an RNN/LSTM, it fails with mentionning that something RNN related is unimplemented. The code runs fine with CPU only.

**Comment by sunway513** [comment]
Hi @mfrey777 , thank you for reporting this issue, we'll try to repro it locally and let you know.

**Comment by sunway513** [comment]
Confirmed the error message locally, assigning to @jerryyin  to take a deeper look.

**Comment by trembous** [comment]
> Just a few more infos. I realised that my linux was running a 5.XX kernel which is not not supported according to ROCM 2.9 installation guide.
> 
> So I tried to runt he same code on a Ubuntu 18.04 with a 4.15.66 kernel (and ROCM 2.9 dkms installed).
> 
> I get the exact same error message than aboce:
> 
> The error message in the first post is the end of it, it however looks like the row below is actually the first row causing the the error.
> 
> 2019-11-02 21:00:45.034231: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cudnn_rnn_ops.cc:1491 : Unimplemented: createRnnDescriptor is unimplemented
> 
> What is strange, is that I can run ANN and CNN succesfully, but the 2 times I tries to run an RNN/LSTM, it fails with mentionning that something RNN related is unimplemented. The code runs fine with CPU only.

the same error in issue#33721, AniTho  said 'the problem was solved after downgrading tensorflow to 1.14' ，it would occur in TF2.0. And if you run on cpu ,it won't crash

**Comment by trembous** [comment]
> > Just a few more infos. I realised that my linux was running a 5.XX kernel which is not not supported according to ROCM 2.9 installation guide.
> > So I tried to runt he same code on a Ubuntu 18.04 with a 4.15.66 kernel (and ROCM 2.9 dkms installed).
> > I get the exact same error message than aboce:
> > The error message in the first post is the end of it, it however looks like the row below is actually the first row causing the the error.
> > 2019-11-02 21:00:45.034231: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cudnn_rnn_ops.cc:1491 : Unimplemented: createRnnDescriptor is unimplemented
> > What is strange, is that I can run ANN and CNN succesfully, but the 2 times I tries to run an RNN/LSTM, it fails with mentionning that something RNN related is unimplemented. The code runs fine with CPU only.
> 
> the same error in issue#33721,you may need to update the cuda to 7.6.2,Use TF_FORCE_GPU_ALLOW_GROWTH=true to force allow GPU growth





> Just a few more infos. I realised that my linux was running a 5.XX kernel which is not not supported according to ROCM 2.9 installation guide.
> 
> So I tried to runt he same code on a Ubuntu 18.04 with a 4.15.66 kernel (and ROCM 2.9 dkms installed).
> 
> I get the exact same error message than aboce:
> 
> The error message in the first post is the end of it, it however looks like the row below is actually the first row causing the the error.
> 
> 2019-11-02 21:00:45.034231: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cudnn_rnn_ops.cc:1491 : Unimplemented: createRnnDescriptor is unimplemented
> 
> What is strange, is that I can run ANN and CNN succesfully, but the 2 times I tries to run an RNN/LSTM, it fails with mentionning that something RNN related is unimplemented. The code runs fine with CPU only.

the same error in issue#33721,you may need to update the cuda to 7.6.2,Use TF_FORCE_GPU_ALLOW_GROWTH=true to force allow GPU growth, the detail in
https://stackoverflow.com/questions/58359153/cancellederror-derived-recvasync-is-cancelled

**Comment by mfrey777** [comment]
Thank you, I also found that post on stackoverflow, but adding that parameter did not help. I tried in 2 different ways, first in the code:

gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

and then to export the variable in the shell, but that did not work either.

I am still getting the same error message.

I was however confused by the Cuda Version part of that past, as I thouth that ROCM was the Cude equivalent for AMD. Do I need to install some Cuda drivers ?

**Comment by jerryyin** [comment]
@mfrey777 Thank you for opening the issue. Apparently this is caused by us letting behind a commit in the 2.0.0 release branch. This will be fixed in 2.1.0. At the same time, could you give `rocm/tensorflow-autobuilds:rocm2.8-f4df78b` image a shot?

> $ docker pull rocm/tensorflow-autobuilds:rocm2.8-f4df78b
   $ alias drun='sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined'
   $ drun rocm/tensorflow-autobuilds:rocm2.8-f4df78b
   \# Execute the script inside this docker container.

Let me know if you run into any issues.

**Comment by mfrey777** [comment]
Thank your for the quick reply. I executing my script in the docker container and it does run, but it does run slower than when I run it with CPU (on a not ROCM Tensorflow 2.0).

Epoch 1 took 541s on the docker image (with GPU enabled, so a Vega 56 8Gb) 
![Screenshot from 2019-11-12 09-40-36](https://user-images.githubusercontent.com/19504497/68655664-b915bc80-0530-11ea-8ac9-7386b1af682f.png)

Running the same code a TF 2.0 (without gpu acceleration) runs about twice as fast (253 s)
![Screenshot from 2019-11-12 09-49-25](https://user-images.githubusercontent.com/19504497/68656241-bbc4e180-0531-11ea-88c2-85ebc49e6359.png)

I tried to run a simple text classification to compare runtimes, so another tutorial from the TF 2.0 website: https://www.tensorflow.org/tutorials/keras/text_classification_with_hub

local Ubuntu 18.04 / Python 3.7.5 / ROCM 2.9 / TF 2.0 upstream
- CPU: 90ms/step
- GPU: 78ms/step
docker image
- GPU: 66ms/step

So the GPU is actually a faster than the CPU

**Comment by ekuznetsov139** [comment]
Your task involves a lot of small operations and the gains from using a GPU are outweighed by the overhead associated with launching each GPU operation. And I think there's some room for improvement in the ROCm stack.

With a Vega 64 / Ryzen 7 1700x, I see 405 s/epoch as in the original post, but 274 s/epoch at batch size 128 (larger batch size - fewer individual ops - less overhead). Unfortunately, it won't go much higher than 128 because it runs out of memory.

Profiling data for the script:

> "Name","Calls","TotalDurationNs","AverageNs","Percentage"
> "Op2dTensorLite",67925,574807248,8462,24.5170400952
> "Cijk_Ailk_Bljk_SB_MT128x64x8_SE_APM1_AF0EM1_AF1EM1_AMAS0_ASEM1_BL0_DTL0_EPS0_FL0_GRVW1_GSU1_ISA000_IU1_K1_KLS_LPA0_LPB0_LDL1_MGWVW1_NLCA1_NLCB1_PK0_PGR0_PLR0_RK0_SU32_SNLL0_TT8_4_USFGRO0_VAW1_VW1_WG16_16_1_WGM8",7018,482528072,68755,20.581090669
> "Cijk_Ailk_Bjlk_SB_MT128x128x8_SE_APM1_AF0EM1_AF1EM1_AMAS0_ASEM1_BL0_DTL0_EPS0_FL0_GRVW1_GSU1_ISA000_IU1_K1_KLS_LPA0_LPB0_LDL1_MGWVW1_NLCA1_NLCB1_PK0_PGR0_PLR0_RK0_SU32_SNLL0_TT8_8_USFGRO0_VAW1_VW1_WG16_16_1_WGM8",21,354002416,16857257,15.0991335914
> "Cijk_Alik_Bljk_SB_MT128x64x12_SE_APM1_AF0EM1_AF1EM1_AMAS0_ASEM1_BL0_DTL0_EPS0_FL0_GRVW1_GSU1_ISA000_IU1_K1_KLS_LPA0_LPB0_LDL1_MGWVW1_NLCA3_NLCB3_PK0_PGR1_PLR1_RK0_SU32_SNLL0_TT8_4_USFGRO0_VAW1_VW1_WG16_16_1_WGM8",8628,290601231,33681,12.3949063915
> "MIOpenActiveFwd2DLite",25847,240416872,9301,10.254411563
> "Op2dTensorSquash",5,189359114,37871822,8.07666397123
> "MIOpenActiveBwd2DLite",21031,177073549,8419,7.55265232951
> "void (anonymous namespace)::hip_fill_n<256u, unsigned int*, unsigned long, unsigned int>(unsigned int*, unsigned long, unsigned int)",48,12642428,263383,0.539232786738
> 

Rows 1, 5, 6, 7 are internal MIOpen helper functions. Rows 2, 3, 4 are GEMM operations:

> 
> ./rocblas-bench -f gemm_ex --transposeA T --transposeB N -m 256 -n 64 -k 64 --alpha 1 --a_type f32_r --lda 64 --b_type f32_r --ldb 384 --beta 1 --c_type f32_r --ldc 384 --d_type f32_r --ldd 384 --compute_type f32_r --algo 0 --solution_index 0 --flags 0
> ./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 64 -n 64 -k 256 --alpha 1 --a_type f32_r --lda 64 --b_type f32_r --ldb 384 --beta 1 --c_type f32_r --ldc 384 --d_type f32_r --ldd 384 --compute_type f32_r --algo 0 --solution_index 0 --flags 0

- mostly tiny (256x64 * 64x64) and executing in ~30 us or less.

**Comment by mfrey777** [comment]
Thank you for the detailed explanation, i makes more sense to me now.

**Comment by wellhowtosay** [comment]
having the same bug on my device when I using keras.layers.LSTM 

> 2019-11-18 04:36:20.298226: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cudnn_rnn_ops.cc:1491 : Unimplemented: createRnnDescriptor is unimplemented
2019-11-18 04:36:20.298246: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unimplemented: createRnnDescriptor is unimplemented


when I used tf.compat.v1.keras.layers.LSTM or tf.keras.layers.RNN, it worked fine ,except it was very slow,actually as slow as training on a CPU, and I deeply doubt that the program **was** running on CPU.

here is a comment on [https://tensorflow.google.cn/api_docs/python/tf/keras/layers/LSTM?hl=en](url)

> Based on available runtime hardware and constraints, this layer will choose different implementations (cuDNN-based or pure-TensorFlow) to maximize the performance. If a GPU is available and all the arguments to the layer meet the requirement of the CuDNN kernel (see below for details), the layer will use a fast cuDNN implementation.

- rocm-dkms  version 2.9.6

- python version 3.6

- Linux version 5.3.11-050311-generic

- TensorFlow version (use command below): 2.0.0 (pip install tensorflow-rocm)

- GPU model and memory: Radeon vii  16Gb 

- OS Platform and Distribution :Ubuntu 18.04.3 LTS

**Comment by Matoran** [comment]
> @mfrey777 Thank you for opening the issue. Apparently this is caused by us letting behind a commit in the 2.0.0 release branch. This will be fixed in 2.1.0. At the same time, could you give `rocm/tensorflow-autobuilds:rocm2.8-f4df78b` image a shot?
> 
> > $ docker pull rocm/tensorflow-autobuilds:rocm2.8-f4df78b
> > $ alias drun='sudo docker run -it --network=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined'
> > $ drun rocm/tensorflow-autobuilds:rocm2.8-f4df78b
> > # Execute the script inside this docker container.
> 
> Let me know if you run into any issues.

@jerryyin Hi, which changes solves the problem? I've tested the image rocm/tensorflow-autobuilds:rocm2.8-f4df78b and it works. But I've tested it on a computer with AVX, now I need to make it work on a computer without AVX instructions. Do I need to compile a specific commit from this repo or the official one ?
